#pragma once

#include "NativeGameplayTags.h"

namespace ADGameplayTags
{
	ARCANEDEFENSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Casting);
	ARCANEDEFENSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Rooted);
	ARCANEDEFENSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_CancelOnMovement);
	ARCANEDEFENSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Root);
	ARCANEDEFENSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_FrostNova);
	ARCANEDEFENSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Meteor);
	ARCANEDEFENSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Resource_Coins);
}